### ISSUE TITLE
Choice of selection

### ISSUE THREAD

**Issue by LivC93** [hexavier/codon_optimization#1]
Apologies for disturbing you, I was looking through this repo and wanted to ask about the choice of metric used :
1. In `1_codoncounts_pergene` line 13 it looks like you take the Mean across multiple rows for the same gene. I wanted to ask why you take the mean and not the mode.
2. In `2_gtex_computePTR` line 32 for each tissue you select the median sample. I wanted to ask why the median and not the mean

Thank you for making this repo available. It really helps reproducing results.

**Comment by hexavier** [comment]
Hi @LivC93 ,
In general terms, there is no specific reason for choosing one metric or the other, the options you suggest should be perfectly correct too (although my guess is that results will not change much). For each point:
1. Taking the mean allowed to consider evenly all known CDS for each gene, not only the most common one. It could be that a CDS that is not the most common is actually the one that is most expressed.
2. Usually the median is more robust to outliers, but I would be surprised if it changed much.
Hope it helps!
